# Generated by Django 4.2.7 on 2023-12-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='momdify_date',
            new_name='modify_date',
        ),
    ]
